name: container-builds
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '15 6 * * *'

jobs:

  buildpack-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: neblioteam/buildpack-deps
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: docker-buildpack-nebliod-deps
          buildargs: GITHUB_SHA


  buildpack-deps-rpi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: neblioteam/buildpack-deps-rpi
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: docker-buildpack-nebliod-deps-rpi
          buildargs: GITHUB_SHA


  nebliod-build-ccache:
    runs-on: ubuntu-latest
    needs: buildpack-deps
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: neblioteam/nebliod-build-ccache
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: docker-nebliod-build-ccache
          buildargs: GITHUB_SHA


  nebliod-build-ccache-rpi:
    runs-on: ubuntu-latest
    needs: buildpack-deps-rpi
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: neblioteam/nebliod-build-ccache-rpi
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: docker-nebliod-build-ccache-rpi
          buildargs: GITHUB_SHA


