name: container-builds
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '15 6 * * *'

jobs:

  buildpack-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: neblioteam/buildpack-deps
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: docker-buildpack-nebliod-deps
          buildargs: GITHUB_SHA


