name: container-builds
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '15 6 * * *'

jobs:

  buildpack-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: neblioteam/buildpack-deps
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: docker-buildpack-nebliod-deps


  buildpack-deps-rpi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: neblioteam/buildpack-deps-rpi
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: docker-buildpack-nebliod-deps-rpi


  nebliod-build-ccache:
    runs-on: ubuntu-latest
    needs: buildpack-deps
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: neblioteam/nebliod-build-ccache
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: docker-nebliod-build-ccache


  nebliod-build-ccache-rpi:
    runs-on: ubuntu-latest
    needs: buildpack-deps-rpi
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: neblioteam/nebliod-build-ccache-rpi
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: docker-nebliod-build-ccache-rpi


  nebliod:
    runs-on: ubuntu-latest
    needs: nebliod-build-ccache
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: neblioteam/nebliod
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


  nebliod-rpi:
    runs-on: ubuntu-latest
    needs: nebliod-build-ccache-rpi
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: neblioteam/nebliod-rpi
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: docker-nebliod-rpi


  nebliod-sync-testnet:
    runs-on: ubuntu-latest
    # needs: nebliod-build-ccache
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 51200 #set root partition to 50GB this is where docker images are stored
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - uses: actions/checkout@master
      - name: Build and Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: neblioteam/nebliod-sync-testnet
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: docker-nebliod-sync-testnet


  nebliod-testnet:
    runs-on: ubuntu-latest
    needs: [nebliod-build-ccache, nebliod-sync-testnet]
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: neblioteam/nebliod-testnet
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: docker-nebliod-testnet


  nebliod-testnet-rpi:
    runs-on: ubuntu-latest
    needs: [nebliod-build-ccache-rpi, nebliod-sync-testnet]
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: neblioteam/nebliod-testnet-rpi
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: docker-nebliod-testnet-rpi


